In [1]:
# Standard libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit Learn
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, make_scorer, silhouette_score, classification_report
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import loguniform
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.feature_selection import SelectKBest, f_classif, mutual_info_classif
from sklearn.neural_network import MLPClassifier

# MiniLearn — your from-scratch library
# from minilearn.classifiers import LogisticRegression, KNN, GaussianNaiveBayes, DecisionTreeClassifier
# from minilearn.preprocessing import StandardScaler, train_test_split
# from minilearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [2]:
# load processed data
metadata = pd.read_csv("/home/westley/Documents/classes/spring_2026/machine_learning/Project_CSE432-532/SER_Project/processed_data/ravdess_metadata.csv")
features = pd.read_csv("/home/westley/Documents/classes/spring_2026/machine_learning/Project_CSE432-532/SER_Project/processed_data/ravdess_features.csv")

# load dataframes
df = metadata.merge(features, on="filename", how="inner")
features = features.drop(columns=["filename"])

In [3]:
X = features.copy()
y = df["emotion"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

MLP = MLPClassifier().fit(X_train_scaled, y_train)

y_pred = MLP.predict(X_test_scaled)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Test Macro F1:", f1_score(y_test, y_pred, average="macro"))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 0.7046843177189409
Test Macro F1: 0.6927133048029216
              precision    recall  f1-score   support

       angry       0.79      0.76      0.78        75
        calm       0.77      0.79      0.78        75
     disgust       0.65      0.56      0.60        39
     fearful       0.70      0.65      0.68        75
       happy       0.70      0.72      0.71        75
     neutral       0.75      0.79      0.77        38
         sad       0.67      0.71      0.69        75
   surprised       0.52      0.56      0.54        39

    accuracy                           0.70       491
   macro avg       0.69      0.69      0.69       491
weighted avg       0.71      0.70      0.70       491

[[57  1  2  4  4  0  4  3]
 [ 0 59  1  2  6  2  5  0]
 [ 4  0 22  1  0  2  3  7]
 [ 5  3  0 49  4  0  9  5]
 [ 5  6  1  4 54  2  2  1]
 [ 0  0  1  2  2 30  2  1]
 [ 0  6  2  3  4  4 53  3]
 [ 1  2  5  5  3  0  1 22]]


/home/westley/Documents/classes/spring_2026/machine_learning/Project_CSE432-532/SER_Project/.venv/lib64/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
from minilearn.neural_network import MLPClassifier

X = features.copy()
y = df["emotion"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

MLP = MLPClassifier(hidden_layer_sizes=100).fit(X_train_scaled, y_train)

y_pred = MLP.predict(X_test_scaled)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Test Macro F1:", f1_score(y_test, y_pred, average="macro"))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 0.5539714867617108
Test Macro F1: 0.5424508589751593
              precision    recall  f1-score   support

       angry       0.63      0.60      0.62        75
        calm       0.62      0.71      0.66        75
     disgust       0.45      0.38      0.42        39
     fearful       0.62      0.51      0.56        75
       happy       0.50      0.56      0.53        75
     neutral       0.66      0.50      0.57        38
         sad       0.47      0.53      0.50        75
   surprised       0.48      0.51      0.49        39

    accuracy                           0.55       491
   macro avg       0.55      0.54      0.54       491
weighted avg       0.56      0.55      0.55       491

[[45  1  3  4 14  1  2  5]
 [ 0 53  2  2  5  1 11  1]
 [ 2  4 15  2  3  1  6  6]
 [ 9  5  2 38  9  1  7  4]
 [ 9  6  2  8 42  1  6  1]
 [ 1  0  2  0  1 19 12  3]
 [ 1 15  3  4  6  4 40  2]
 [ 4  2  4  3  4  1  1 20]]


In [ ]:
X = features.copy()
y = df["emotion"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

pipeline = Pipeline([("scaler", StandardScaler()), ("model", MLPClassifier( max_iter=1000, random_state=42))])

param_dist = {
    "model__hidden_layer_sizes": [(64,), (128,), (256,), (128, 64), (256, 128), (256, 128, 64)],
    "model__activation": ["relu", "tanh"],
    "model__alpha": loguniform(1e-5, 1e-2),
    "model__learning_rate_init": loguniform(1e-4, 1e-2),
    "model__batch_size": [16, 32, 64]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

search = RandomizedSearchCV(pipeline, param_distributions=param_dist, n_iter=30, scoring="f1_macro", cv=cv, random_state=42, n_jobs=-1).fit(X_train, y_train)

print("Best params:", search.best_params_)
print("Best CV macro F1:", search.best_score_)

best_model = search.best_estimator_
y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Test Macro F1:", f1_score(y_test, y_pred, average="macro"))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Best params: {'model__activation': 'relu', 'model__alpha': np.float64(0.00764743990754351), 'model__batch_size': 16, 'model__hidden_layer_sizes': (256, 128), 'model__learning_rate_init': np.float64(0.00034889766548903674)}
Best CV macro F1: 0.7016781344599938
Test Accuracy: 0.7331975560081466
Test Macro F1: 0.7251832011511201
              precision    recall  f1-score   support

       angry       0.75      0.75      0.75        75
        calm       0.77      0.84      0.80        75
     disgust       0.71      0.56      0.63        39
     fearful       0.69      0.71      0.70        75
       happy       0.79      0.69      0.74        75
     neutral       0.82      0.84      0.83        38
         sad       0.70      0.77      0.73        75
   surprised       0.63      0.62      0.62        39

    accuracy                           0.73       491
   macro avg       0.73      0.72      0.73       491
weighted avg       0.73      0.73      0.73       491

[[56  0  3  7  3  1  

While this is an improvement over the SVC model, I'm honestly a little disappointed that the difference isn't greater. I only really squeezed out an additional 3% accuracy. I'm also not entirely sure where to go from here.

In [4]:
X = features.copy()
y = df["emotion"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

pipeline = Pipeline([("scaler", StandardScaler()), ("model", MLPClassifier( max_iter=1000, random_state=42))])

param_dist = {
    "model__hidden_layer_sizes": [(128, 64), (256, 128), (256, 128, 64)],
    "model__activation": ["relu"],
    "model__alpha": loguniform(1e-4, 1e-1),
    "model__learning_rate_init": loguniform(1e-5, 1e-3),
    "model__batch_size": [12, 16, 20]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

search = RandomizedSearchCV(pipeline, param_distributions=param_dist, n_iter=30, scoring="f1_macro", cv=cv, random_state=42, n_jobs=-1).fit(X_train, y_train)

print("Best params:", search.best_params_)
print("Best CV macro F1:", search.best_score_)

best_model = search.best_estimator_
y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Test Macro F1:", f1_score(y_test, y_pred, average="macro"))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

/home/westley/Documents/classes/spring_2026/machine_learning/Project_CSE432-532/SER_Project/.venv/lib64/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/westley/Documents/classes/spring_2026/machine_learning/Project_CSE432-532/SER_Project/.venv/lib64/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/westley/Documents/classes/spring_2026/machine_learning/Project_CSE432-532/SER_Project/.venv/lib64/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/westley/Documents/classes/spring_2026

Best params: {'model__activation': 'relu', 'model__alpha': np.float64(0.01355154055297657), 'model__batch_size': 16, 'model__hidden_layer_sizes': (256, 128), 'model__learning_rate_init': np.float64(7.562632622090494e-05)}
Best CV macro F1: 0.7190916879419755
Test Accuracy: 0.7515274949083504
Test Macro F1: 0.7437681491978078
              precision    recall  f1-score   support

       angry       0.79      0.83      0.81        75
        calm       0.79      0.84      0.81        75
     disgust       0.67      0.62      0.64        39
     fearful       0.77      0.68      0.72        75
       happy       0.76      0.71      0.73        75
     neutral       0.85      0.87      0.86        38
         sad       0.70      0.77      0.73        75
   surprised       0.64      0.64      0.64        39

    accuracy                           0.75       491
   macro avg       0.75      0.74      0.74       491
weighted avg       0.75      0.75      0.75       491

[[62  0  3  2  4  1  2

In [ ]:
X = features.copy()
y = df["emotion"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

pipeline = Pipeline([("scaler", StandardScaler()), ("model", MLPClassifier( max_iter=1000, random_state=42))])

param_dist = {
    "model__hidden_layer_sizes": [(256, 128)],
    "model__activation": ["relu"],
    "model__alpha": np.float64(0.01355154055297657),
    "model__learning_rate_init": np.float64(7.562632622090494e-05),
    "model__batch_size": [16]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

search = RandomizedSearchCV(pipeline, param_distributions=param_dist, n_iter=30, scoring="f1_macro", cv=cv, random_state=42, n_jobs=-1).fit(X_train, y_train)

print("Best params:", search.best_params_)
print("Best CV macro F1:", search.best_score_)

best_model = search.best_estimator_
y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Test Macro F1:", f1_score(y_test, y_pred, average="macro"))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))